### ISSUE TITLE
ss - User's guess/solution is compared against the answer recorded on the correct row of the `Game` table.

### ISSUE THREAD

**Issue by jacob-bw** [jacob-bw/Insert-Knife#23]
## User Story
As a user who is trying to solve a mystery, I would like for my proposed solution to be compared to the known answer, and for the results of that comparison to be returned to me.

## AC
- [ ] When a guess is made, as laid out in #21 + #22, it will need to be in the format of `Weapon`, `Suspect`, `Room`
- [ ] The Ids for the values of the User's guess should be compared against the answerRoomId, answerWeaponId, and answerSuspectId on the `Game` table respectively.
- [ ] This function should confirm that the Room Id entered is the current room by checking the currentRoomId in the `Game` table
- [ ]This function should also validate the values of the Guess by comparing them against the total options for Room, Weapon, and Suspect.
- [ ] If a User submits an invalid value as part of a guess (e.g. incorrect order, or a value that doesn't exist, such as "Dr Pink"), return an error of One or more of the values you specified are invalid. Please resubmit your answer in the format of '[Suspect], [Weapon], [Room]'
- [ ] If the user submits a Room as part of their answer that isn't the room they are currently in, return an error of `Sorry, you cannot make a guess involving a room that you don't currently occupy. Please either resubmit your guess for the [current room], or move to your desired room.`
- [ ] If the User's guess is incorrect, populate the values in the incorrect guess table as laid out in #21
- [ ] If the User's guess is correct, return the "you solved the murder" toast (ticket #26 ).
