### ISSUE TITLE
UPDATE List of All API Endpoints

### ISSUE THREAD

**Issue by jacob-bw** [jacob-bw/Insert-Knife#28]
## HTTPGET

- [x] view all games `api/games/allgames`
- [ ] view current saved game `api/games/currentgame`
- [ ] games won vs lost `api/games/gameswon` (ui stretch goal)
- [ ] resume current saved game `api/games/loadgame/{gameId}`
- [x] view previous guesses `api/user/{userId}/guesses` (#21)

## HTTPPOST

- [x] start new game `api/games/newgame` (#14 )
- [ ] user can attempt to solve the puzzle `api/guess/newguess` (#22)

## HTTPPUT

- [ ] save current game `api/user/savegame` (#17 + #16 )
